<h2 style="color:purple" align="center"> Saving Model to a File</h2>


<img src="saving.jpg">



In [1]:
import pandas as pd 
from sklearn import linear_model 
import numpy as np

In [2]:
df=pd.read_csv("data/homeprices.csv")

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

<h3>Handling missing Data </h3>

the best option in this case is to have median 


In [4]:
import math 
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

4

In [5]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
reg=linear_model.LinearRegression()

In [7]:
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [8]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [9]:
reg.intercept_

221323.00186540384

### python pickle model to save model 

In [19]:
import pickle 
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)
    

### python pickle model to read model

In [20]:
with open('model_pickle','rb') as t:
    mp=pickle.load(t)

In [22]:
mp.predict([[3000,3,40]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [20]:
reg.predict([[3000,3,40]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

## JOBLIB

when you have more numpy array joblib tend to be more efficient 

In [25]:
import joblib

In [26]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [28]:
mj=joblib.load('model_joblib')

In [29]:
mj.predict([[3000,3,40]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [30]:
mj.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [32]:
mj.intercept_

221323.00186540384